Repository Festimate/Festimate-iOS, pull requests merged in 2024-11, with the labels that each got.

#12 Feature/#9
  Festimate-iOS/Festimate-iOS/Global/Extensions/UILabel+.swift
  Festimate-iOS/Festimate-iOS/Global/Extensions/UITextField+.swift
  Festimate-iOS/Festimate-iOS/Global/Resources/Assets.xcassets/Assets/kakao_logo.imageset/Contents.json
  Festimate-iOS/Festimate-iOS/Global/Resources/Assets.xcassets/Assets/kakao_logo.imageset/카카오 로고.svg
  Festimate-iOS/Festimate-iOS/Global/Resources/Assets.xcassets/Assets/main_logo.imageset/Contents.json
  Festimate-iOS/Festimate-iOS/Global/Resources/Assets.xcassets/Assets/main_logo.imageset/main_logo 1.png
  Festimate-iOS/Festimate-iOS/Global/Resources/Assets.xcassets/Assets/main_logo.imageset/main_logo 2.png
  Festimate-iOS/Festimate-iOS/Global/Resources/Assets.xcassets/Assets/main_logo.imageset/main_logo.png
  Festimate-iOS/Festimate-iOS/Global/UIComponents/FestimateTextField.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Login/Models/ButtonState.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Login/Models/Gender.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Login/Models/RegisterStep.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Login/Models/ValidationState.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Login/ViewControllers/FirstUserInfoViewController.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Login/ViewControllers/LoginViewController.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Login/ViewControllers/RegisterViewController.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Login/ViewControllers/SecondUserInfoViewController.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Login/ViewControllers/ThirdUserInfoViewController.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Login/ViewModel/RegisterSideEffect.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Login/ViewModel/RegisterState.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Login/ViewModel/RegisterViewModel.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Login/Views/FirstUserInfoView.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Login/Views/LoginView.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Login/Views/RegisterView.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Login/Views/SecondUserInfoView.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Login/Views/ThirdUserInfoView.swift
Labels: 💡feature💡

#13 [Feat] 이상형 정보 입력 UI 구현 (#10)
  Festimate-iOS/Festimate-iOS/Global/Extensions/UITextField+.swift
  Festimate-iOS/Festimate-iOS/Global/Resources/Assets.xcassets/Assets/kakao_logo.imageset/Contents.json
  Festimate-iOS/Festimate-iOS/Global/Resources/Assets.xcassets/Assets/kakao_logo.imageset/카카오 로고 1.svg
  Festimate-iOS/Festimate-iOS/Global/UIComponents/SelectButtonCollectionViewCell.swift
  Festimate-iOS/Festimate-iOS/Global/Utils/Enums/AvailableTime.swift
  Festimate-iOS/Festimate-iOS/Global/Utils/Enums/FaceType.swift
  Festimate-iOS/Festimate-iOS/Global/Utils/Enums/MBTIType.swift
  Festimate-iOS/Festimate-iOS/Presentaion/AddMatching/Models/AddMatchingModel.swift
  Festimate-iOS/Festimate-iOS/Presentaion/AddMatching/ViewControllers/AddMatchingViewController.swift
  Festimate-iOS/Festimate-iOS/Presentaion/AddMatching/ViewControllers/IdealTypeInputStep1ViewController.swift
  Festimate-iOS/Festimate-iOS/Presentaion/AddMatching/ViewControllers/IdealTypeInputStep2ViewController.swift
  Festimate-iOS/Festimate-iOS/Presentaion/AddMatching/Views/AddMatchingView.swift
  Festimate-iOS/Festimate-iOS/Presentaion/AddMatching/Views/IdealTypeInputStep1View.swift
  Festimate-iOS/Festimate-iOS/Presentaion/AddMatching/Views/IdealTypeInputStep2View.swift
  Festimate-iOS/Festimate-iOS/Presentaion/GoToMatching/ViewControllers/AvailableTimeViewController.swift
  Festimate-iOS/Festimate-iOS/Presentaion/GoToMatching/ViewControllers/DressInfoViewController.swift
Labels: 💡feature💡, 🌀민서공이🌀

#17 [FEAT] 유저 상세 정보 조회 네트워크 통신 (#16)
  Festimate-iOS/Festimate-iOS.xcodeproj/project.pbxproj
  Festimate-iOS/Festimate-iOS/Global/Resources/Assets.xcassets/Assets/kakao.imageset/Contents.json
  Festimate-iOS/Festimate-iOS/Global/Resources/Assets.xcassets/Assets/kakao.imageset/카카오 로고.svg
  Festimate-iOS/Festimate-iOS/Network/Base/NetworkService.swift
  Festimate-iOS/Festimate-iOS/Network/User/DTO/GetUserDetailResponse.swift
  Festimate-iOS/Festimate-iOS/Network/User/UserService.swift
  Festimate-iOS/Festimate-iOS/Network/User/UserTargetType.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Login/Views/LoginView.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Main/ViewControllers/MainViewController.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Main/Views/MainView.swift
Labels: 💡feature💡, 🌀민서공이🌀

#21 [FIX] 버그 수정 (#20)
  Festimate-iOS/Festimate-iOS.xcodeproj/project.pbxproj
  Festimate-iOS/Festimate-iOS/Presentaion/AddMatching/ViewControllers/IdealTypeInputStep1ViewController.swift
  Festimate-iOS/Festimate-iOS/Presentaion/GoToMatching/ViewControllers/DressInfoViewController.swift
  Festimate-iOS/Festimate-iOS/Presentaion/GoToMatching/Views/DressInfoView.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Main/Cells/matchingCardCollectionViewCell.swift
  Festimate-iOS/Festimate-iOS/Presentaion/Main/Views/MainView.swift
Labels: 🛠️fix🛠️, 🌀민서공이🌀
